# Generated by Django 4.0.6 on 2022-11-17 04:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnkenKanjokamoku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ankenKanjokamokuCode', models.IntegerField(blank=True, null=True)),
                ('ankenKanjokamoku', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'ankenKanjokamokuTable',
            },
        ),
        migrations.CreateModel(
            name='AnkenList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keiriShonin', models.BooleanField(blank=True, null=True)),
                ('statusCode', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('edabanGroup', models.IntegerField(blank=True, null=True)),
                ('shiharaiPattern', models.IntegerField(blank=True, null=True)),
                ('kanriNo', models.CharField(blank=True, max_length=30, null=True)),
                ('edaban', models.CharField(blank=True, max_length=30, null=True)),
                ('ankenMei', models.CharField(blank=True, max_length=100, null=True)),
                ('torihikisakiCode', models.IntegerField(blank=True, null=True)),
                ('torihikisakiMei', models.CharField(blank=True, max_length=30, null=True)),
                ('kanjokamokuCode', models.IntegerField(blank=True, null=True)),
                ('kanjokamoku', models.CharField(blank=True, max_length=30, null=True)),
                ('keikakuTanka', models.IntegerField(blank=True, null=True)),
                ('keikakuSuu', models.IntegerField(blank=True, null=True)),
                ('keikakuGokei', models.IntegerField(blank=True, null=True)),
                ('mitsumoriTanka', models.IntegerField(blank=True, null=True)),
                ('mitsumoriSuu', models.IntegerField(blank=True, null=True)),
                ('mitsumoriGokei', models.IntegerField(blank=True, null=True)),
                ('mitsumoriLink', models.URLField(blank=True, null=True)),
                ('ringiTanka', models.IntegerField(blank=True, null=True)),
                ('ringiSuu', models.IntegerField(blank=True, null=True)),
                ('ringiGokei', models.IntegerField(blank=True, null=True)),
                ('ringishoNo', models.CharField(blank=True, max_length=30, null=True)),
                ('ringishoLink', models.URLField(blank=True, null=True)),
                ('wfNo', models.CharField(blank=True, max_length=30, null=True)),
                ('keiyakuKingaku', models.IntegerField(blank=True, null=True)),
                ('keiyakushoNo', models.CharField(blank=True, max_length=30, null=True)),
                ('keiyakushoLink', models.URLField(blank=True, null=True)),
                ('onatsuRingiNo', models.CharField(blank=True, max_length=30, null=True)),
                ('onatsuRingiLink', models.URLField(blank=True, null=True)),
                ('chumonTanka', models.IntegerField(blank=True, null=True)),
                ('chumonSuu', models.IntegerField(blank=True, null=True)),
                ('chumonGokei', models.IntegerField(blank=True, null=True)),
                ('chumonLink', models.URLField(blank=True, null=True)),
                ('nohinKigen', models.DateField(blank=True, null=True)),
                ('shiharaiKigen', models.DateField(blank=True, null=True)),
                ('nohinTanka', models.IntegerField(blank=True, null=True)),
                ('nohinSuu', models.IntegerField(blank=True, null=True)),
                ('nohinGokei', models.IntegerField(blank=True, null=True)),
                ('nohinLink', models.URLField(blank=True, null=True)),
                ('shiharaiTanka', models.IntegerField(blank=True, null=True)),
                ('konyuSuu', models.IntegerField(blank=True, null=True)),
                ('konyuGokei', models.IntegerField(blank=True, null=True)),
                ('seikyushoLink', models.URLField(blank=True, null=True)),
                ('keikaku_Jisseki', models.IntegerField(blank=True, null=True)),
                ('kurikaeshiKigen', models.DateField(blank=True, null=True)),
                ('konyuKaisha', models.CharField(blank=True, max_length=30, null=True)),
                ('dataKoshinbi', models.DateTimeField(default=datetime.datetime.now)),
                ('saishuKoshinsha', models.CharField(blank=True, max_length=30, null=True)),
                ('shainNo', models.IntegerField(blank=True, null=True)),
                ('tantosha', models.CharField(blank=True, max_length=30, null=True)),
                ('comment', models.CharField(blank=True, max_length=30, null=True)),
                ('hyojijun', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ankenListTable',
            },
        ),
        migrations.CreateModel(
            name='AnkenShiharaiPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ankenShiharaiPatternCode', models.IntegerField(blank=True, null=True)),
                ('abkenShiharaiPattern', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'ankenShiharaiPatternTable',
            },
        ),
        migrations.CreateModel(
            name='AnkenStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ankenStatusCode', models.IntegerField(blank=True, null=True)),
                ('ankenStatus', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'ankenStatusTable',
            },
        ),
        migrations.CreateModel(
            name='AnkenTantosha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ankenTantoshaCode', models.IntegerField(blank=True, null=True)),
                ('ankenTantoshaMei', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'ankenTantoshaTable',
            },
        ),
        migrations.CreateModel(
            name='AnkenTorihikisaki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ankenTorihikisakiCode', models.IntegerField(blank=True, null=True)),
                ('ankenTorihikisakiKaisha', models.CharField(blank=True, max_length=30, null=True)),
                ('ankenTorihikisakiTantosha', models.CharField(blank=True, max_length=30, null=True)),
                ('ankenTorihikisakiJusho', models.CharField(blank=True, max_length=30, null=True)),
                ('ankenTorihikisakiTel', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'ankenTorihikisakiTable',
            },
        ),
    ]
